language: php
php:
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
install:
  - travis_retry composer install --no-interaction
script:
  - ./vendor/bin/phpunit
cache:
  directories:
  - vendor